apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  root-password: "REPLACE_WITH_SECURE_PASSWORD"  # Change in production!
  user: "inventory_user"
  password: "REPLACE_WITH_SECURE_PASSWORD"  # Change in production!
